# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/nx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/nx/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/nx/build/CMakeFiles /root/nx/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/nx/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named algo

# Build rule for target.
algo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algo
.PHONY : algo

# fast build rule for target.
algo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/build
.PHONY : algo/fast

#=============================================================================
# Target rules for targets named modnet_test

# Build rule for target.
modnet_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modnet_test
.PHONY : modnet_test

# fast build rule for target.
modnet_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/modnet_test.dir/build.make CMakeFiles/modnet_test.dir/build
.PHONY : modnet_test/fast

build.o: build.cu.o
.PHONY : build.o

# target to build an object file
build.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build.cu.o
.PHONY : build.cu.o

build.i: build.cu.i
.PHONY : build.i

# target to preprocess a source file
build.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build.cu.i
.PHONY : build.cu.i

build.s: build.cu.s
.PHONY : build.s

# target to generate assembly for a file
build.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build.cu.s
.PHONY : build.cu.s

modnet_test.o: modnet_test.cpp.o
.PHONY : modnet_test.o

# target to build an object file
modnet_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/modnet_test.dir/build.make CMakeFiles/modnet_test.dir/modnet_test.cpp.o
.PHONY : modnet_test.cpp.o

modnet_test.i: modnet_test.cpp.i
.PHONY : modnet_test.i

# target to preprocess a source file
modnet_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/modnet_test.dir/build.make CMakeFiles/modnet_test.dir/modnet_test.cpp.i
.PHONY : modnet_test.cpp.i

modnet_test.s: modnet_test.cpp.s
.PHONY : modnet_test.s

# target to generate assembly for a file
modnet_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/modnet_test.dir/build.make CMakeFiles/modnet_test.dir/modnet_test.cpp.s
.PHONY : modnet_test.cpp.s

src/engine.o: src/engine.cu.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cu.o
.PHONY : src/engine.cu.o

src/engine.i: src/engine.cu.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cu.i
.PHONY : src/engine.cu.i

src/engine.s: src/engine.cu.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cu.s
.PHONY : src/engine.cu.s

src/modnet.o: src/modnet.cpp.o
.PHONY : src/modnet.o

# target to build an object file
src/modnet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/modnet.cpp.o
.PHONY : src/modnet.cpp.o

src/modnet.i: src/modnet.cpp.i
.PHONY : src/modnet.i

# target to preprocess a source file
src/modnet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/modnet.cpp.i
.PHONY : src/modnet.cpp.i

src/modnet.s: src/modnet.cpp.s
.PHONY : src/modnet.s

# target to generate assembly for a file
src/modnet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/modnet.cpp.s
.PHONY : src/modnet.cpp.s

src/utils/draw.o: src/utils/draw.cpp.o
.PHONY : src/utils/draw.o

# target to build an object file
src/utils/draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/draw.cpp.o
.PHONY : src/utils/draw.cpp.o

src/utils/draw.i: src/utils/draw.cpp.i
.PHONY : src/utils/draw.i

# target to preprocess a source file
src/utils/draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/draw.cpp.i
.PHONY : src/utils/draw.cpp.i

src/utils/draw.s: src/utils/draw.cpp.s
.PHONY : src/utils/draw.s

# target to generate assembly for a file
src/utils/draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/draw.cpp.s
.PHONY : src/utils/draw.cpp.s

src/utils/preprocess.o: src/utils/preprocess.cpp.o
.PHONY : src/utils/preprocess.o

# target to build an object file
src/utils/preprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/preprocess.cpp.o
.PHONY : src/utils/preprocess.cpp.o

src/utils/preprocess.i: src/utils/preprocess.cpp.i
.PHONY : src/utils/preprocess.i

# target to preprocess a source file
src/utils/preprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/preprocess.cpp.i
.PHONY : src/utils/preprocess.cpp.i

src/utils/preprocess.s: src/utils/preprocess.cpp.s
.PHONY : src/utils/preprocess.s

# target to generate assembly for a file
src/utils/preprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/preprocess.cpp.s
.PHONY : src/utils/preprocess.cpp.s

usr/local/TensorRT-8.5.1.7/samples/common/logger.o: usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.o
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.o

# target to build an object file
usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.o
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.o

usr/local/TensorRT-8.5.1.7/samples/common/logger.i: usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.i
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.i

# target to preprocess a source file
usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.i
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.i

usr/local/TensorRT-8.5.1.7/samples/common/logger.s: usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.s
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.s

# target to generate assembly for a file
usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.s
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/logger.cpp.s

usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.o: usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.o
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.o

# target to build an object file
usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.o
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.o

usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.i: usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.i
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.i

# target to preprocess a source file
usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.i
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.i

usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.s: usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.s
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.s

# target to generate assembly for a file
usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.s
.PHONY : usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... algo"
	@echo "... build"
	@echo "... engine"
	@echo "... modnet_test"
	@echo "... utils"
	@echo "... build.o"
	@echo "... build.i"
	@echo "... build.s"
	@echo "... modnet_test.o"
	@echo "... modnet_test.i"
	@echo "... modnet_test.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/modnet.o"
	@echo "... src/modnet.i"
	@echo "... src/modnet.s"
	@echo "... src/utils/draw.o"
	@echo "... src/utils/draw.i"
	@echo "... src/utils/draw.s"
	@echo "... src/utils/preprocess.o"
	@echo "... src/utils/preprocess.i"
	@echo "... src/utils/preprocess.s"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/logger.o"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/logger.i"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/logger.s"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.o"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.i"
	@echo "... usr/local/TensorRT-8.5.1.7/samples/common/sampleUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

